### ISSUE TITLE
Can't use agent on openshift server

### ISSUE THREAD

**Issue by kommancs96** [logicalparadox/apnagent#35]
I'm developing a website , that should send push notifications to iOS devices. On my localhost apnagent works fine, but when I `git push` it to Openshift cloud I get the following errors in the terminal:
```
remote: Waiting for application port (8080) become available ...
remote: Application 'apnagent' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 55c3344c89f5cf720xxxxxxx (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/55c3344c89f5cf720xxxxxxx/nodejs
remote: #<IO:0x00000000f1c278>
remote: #<IO:0x00000000f1c200>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://55c3344c89f5cf720xxxxxxx@apnagent-xxxxxxx.rhcloud.com/~/git/apnagent.git/
   bbcf2a3..87exxxx  master -> master 
```
My package.json looks like this:
```javascript
{
  "private": true,
  "name": "apnagent",
  "version": "0.0.0",
  "dependencies": {
    "apnagent": "1.0.x"
  },
  "engines": {
    "node": ">=0.10.22",
    "npm": ">=1.3.14"
  },
  "scripts": {
    "start": "node agent/_header.js"
  },
  "main": "agent/_header.js"
}
```
I think i should use somehow `process.env.OPENSHIFT_NODEJS_PORT` as port on the server, or something like this. I'm sure, I've done some configuration mistake since on my local machine everything works fine.

**Comment by pasupulaphani** [comment]
same issue. Any solution?

**Comment by ExploreMqt** [comment]
I can't say that I've tried OpenShift, but I've been using Heroku without
any issues for a few months.
Can you post some example code on how you construct your agent object?

**Comment by iamdangerous** [comment]
same issue, Exactly same error activating gear

**Comment by ajostergaard** [comment]
This might help: https://developers.openshift.com/en/node-js-environment-variables.html

**Comment by iamdangerous** [comment]
Thank you @ajostergaard  for quick reply , i have tried your solution it is working perfectly . But when i include package body-parser and morgan , it results the same error 

my code: 
var express = require('express');
var bodyParser=require('body-Parser');
var morgan=require('morgan');
var app = express();
var http = require('http');

app.use(bodyParser.urlencoded({extended:true}));
app.use(bodyParser.json());
app.use(morgan('dev'));


app.get('/', function (req, res) {
  res.send('Hello World!');
});

var ipaddress = process.env.OPENSHIFT_NODEJS_IP;
var port = process.env.OPENSHIFT_NODEJS_PORT;
if(typeof ipaddress === "undefined"){
	ipaddress = "127.0.0.1";
	port = 3000;
}
app.listen(port, ipaddress, function() {
    // Do your stuff
    console.log("Your server is running on: "+ipaddress+" port:"+port);
});

if i comment out all the packages excluding express, it works fine ...

**Comment by ajostergaard** [comment]
@iamdangerous I suggest making sure it works locally before trying it on openshift however clearly not an apnagent issue.

@kommancs96 i suggest closing this issue.

**Comment by iamdangerous** [comment]
well its working 100% fine in local machine, please look at this post (the answer) , i want to know is there any to use node version 0.12.X , i mean the latest version  in server side (on openshift)

**Comment by ajostergaard** [comment]
Be that as it may this has nothing to do with apnagent.

Have you tried node 10 on your local machine?

**Comment by iamdangerous** [comment]
@ajostergaard  thanks for keeping patience , and helping me everytime, i am an idiot, i was ignoring it all the time ,it was my silly mistake my 2nd line of code -->var bodyParser=require('body-Parser');<-- this was creating issue,  i was importing wrong package all the time the package should be 'body-parser' (case-sensitive) .. 
Now , everything is working fine locally and remotely . Again thanks for your help .

**Comment by srvsud** [comment]
most of the times this issue occurs because of the error in scripts or compilation silly human errors :)
