### ISSUE TITLE
APN agent connected coming false

### ISSUE THREAD

**Issue by vabnirvana** [logicalparadox/apnagent#36]
Hi,
I was earlier able to send notifications using the below code. 

agent
        .set('cert file', join(__dirname, 'certfile.pem'))
        .set('key file', join(__dirname, 'key.pem'))
        .enable('sandbox');

    agent
        .set('expires', '1d')
        .set('reconnect delay', '1s')
        .set('passphrase', 'password')
        .set('cache ttl', '30m');

    agent.on('message:error', function (err, msg) {
        if(err) {
            console.log(err);
        }else{
            console.log(msg);
        }
    });

    agent.connect(function (err) {
        if (err && err.name === 'GatewayAuthorizationError') {
            console.log('Authentication Error: %s', err.message);
            process.exit(1);
        }

        // handle any other err (not likely)
        else if (err) {
            throw err;
        }

        // it worked!
        var env = agent.enabled('sandbox')
            ? 'sandbox'
            : 'production';

        console.log('apnagent [%s] gateway connected', env);
    });

But suddenly, the agent has stopped connecting. eg when i console agent it shows :

{ _drip: { delimeter: ':', wildcard: true },
data:    :11930 -   connected: false,
data:    :11930 -   settings: 
data:    :11930 -    { 'cache ttl': '30m',
data:    :11930 -      codec: 'enhanced',
data:    : 11930 -      } 

It is not throwing an error neither is it sending messages. Any leads would be great. Thanks.

**Comment by countravioli** [comment]
Certs have 12month live spans I think. Login to the Apple's console where you generate them and make sure yours is still valid. I had something similar happen and the error was dug pretty deep in and didn't really bubble up to the end user.

**Comment by vabnirvana** [comment]
That was the issue. Thanks @countravioli .
